openapi: 3.0.3
info:
  description: "API for managing railway stations, parks, ways, locomotives, and wagons."
  title: Railway Station API
  version: 1.0.0
servers:
- url: http://0.0.0.0:8080
paths:
  /stations:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StationShort'
                type: array
          description: OK
      summary: Get a list of stations
      x-accepts: application/json
  /stations/{id}:
    get:
      parameters:
      - description: Station ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Station'
          description: OK
        "400":
          description: Bad Request
      summary: Get information about a specific station
      x-accepts: application/json
  /park/{id}:
    get:
      parameters:
      - description: Park ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Park'
          description: OK
        "400":
          description: Bad Request
      summary: Get information about a specific park
      x-accepts: application/json
  /way/{id}:
    get:
      parameters:
      - description: Way ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Way'
          description: OK
        "400":
          description: Bad Request
      summary: Get information about a specific way
      x-accepts: application/json
  /wagon/{id}:
    get:
      parameters:
      - description: ID of the wagon to retrieve
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WagonResponse'
          description: Successful response
        "400":
          description: Bad request
        "404":
          description: Wagon not found
      summary: Get wagon by ID
      x-accepts: application/json
components:
  schemas:
    WagonResponse:
      example:
        isSick: true
        owner: owner
        idleDaysLength: 1
        note2: note2
        operationState: operationState
        isWithHatch: true
        type: type
        parkId: 7
        wayId: 3
        inventoryNumber: inventoryNumber
        isDirty: true
        daysToRepair: 5
        loadCapacity: 5.962133916683182
        id: 0
        position: 6
        cargo:
          cargoType: cargoType
        kilometersLeft: 2
        note1: note1
        stationId: 9
      properties:
        id:
          type: integer
        inventoryNumber:
          type: string
        position:
          type: integer
        type:
          type: string
        isSick:
          type: boolean
        cargo:
          $ref: '#/components/schemas/Cargo'
        operationState:
          type: string
        idleDaysLength:
          type: integer
        owner:
          type: string
        isWithHatch:
          type: boolean
        loadCapacity:
          type: number
        daysToRepair:
          type: integer
        kilometersLeft:
          type: integer
        isDirty:
          type: boolean
        note1:
          type: string
        note2:
          type: string
        parkId:
          type: integer
        stationId:
          type: integer
        wayId:
          type: integer
      type: object
    Cargo:
      example:
        cargoType: cargoType
      properties:
        cargoType:
          type: string
      type: object
    StationShort:
      example:
        id: 0
        isLoginStation: true
        title: title
      properties:
        id:
          type: integer
        title:
          type: string
        isLoginStation:
          type: boolean
      type: object
    Station:
      example:
        parksCount: 6
        id: 0
        isLoginStation: true
        title: title
        parksIds:
        - 1
        - 1
      properties:
        id:
          type: integer
        title:
          type: string
        isLoginStation:
          type: boolean
        parksCount:
          type: integer
        parksIds:
          items:
            type: integer
          type: array
      type: object
    Park:
      example:
        name: name
        id: 0
        waysCount: 1
        waysIds:
        - 5
        - 5
        stationId: 6
      properties:
        id:
          type: integer
        stationId:
          type: integer
        name:
          type: string
        waysCount:
          type: integer
        waysIds:
          items:
            type: integer
          type: array
      type: object
    Way:
      example:
        maxCarriagesCount: 2
        wagonsIds:
        - 5
        - 5
        wagonsCount: 5
        name: name
        id: 0
        locomotives:
        - inventoryNumber: inventoryNumber
          id: 1
          direction: LEFT
        - inventoryNumber: inventoryNumber
          id: 1
          direction: LEFT
        parkId: 6
      properties:
        id:
          type: integer
        parkId:
          type: integer
        name:
          type: string
        locomotives:
          items:
            $ref: '#/components/schemas/Locomotive'
          type: array
        wagonsCount:
          type: integer
        wagonsIds:
          items:
            type: integer
          type: array
        maxCarriagesCount:
          type: integer
      type: object
    Locomotive:
      example:
        inventoryNumber: inventoryNumber
        id: 1
        direction: LEFT
      properties:
        id:
          type: integer
        inventoryNumber:
          type: string
        direction:
          enum:
          - LEFT
          - RIGHT
          type: string
      type: object

